### ISSUE TITLE
Https to http

### ISSUE THREAD

**Issue by cgarnier** [kylepaulsen/ResourceOverride#14]
Hello,
Is there a way to override a https resource with a http one ? My browser is blocking it.
(Mixed Content)

**Comment by kylepaulsen** [comment]
Not really... Chrome will block those by default if the site is on https. You'll probably have to set up an https server.

**Comment by cgarnier** [comment]
I fact with chrome we can disable this security by clicking on the "shield" in the address bar.
So it s not an issue.
Maybe you can just add it on the doc.

**Comment by cgarnier** [comment]
![unsafe](https://user-images.githubusercontent.com/1249958/30103525-34d19270-92f3-11e7-8229-ecd53e591d6e.gif)

**Comment by kylepaulsen** [comment]
Oh neat, thanks for showing me.
