### ISSUE TITLE
Console fills up with "Resource Override" info

### ISSUE THREAD

**Issue by joeldbirch** [kylepaulsen/ResourceOverride#19]
When I browse a site for which I have override rules set up but deactivated the console is filled with repeated items stating that the rule is off, etc., as in [this screenshot](https://user-images.githubusercontent.com/75602/34545675-9124037a-f142-11e7-95f6-64b87aacb2c7.png). These can be filtered out by disabling info-level items but that also filters other useful console messages. Can you suggest a way around this please?

**Comment by kylepaulsen** [comment]
Make sure 'show logs' is unchecked:
![screen shot 2018-01-04 at 1](https://user-images.githubusercontent.com/865580/34585474-b2753190-f154-11e7-8183-20b32f4071a0.png)

**Comment by joeldbirch** [comment]
Oh, that works. Thank you!
