### ISSUE TITLE
Edit file in an external editor

### ISSUE THREAD

**Issue by norbertpy** [kylepaulsen/ResourceOverride#2]
@kylepaulsen, first of all thanks for this awesome extension. Very clever and very handy. To be honest the UI to edit the file is not very friendly. The `find` bar disappears on the first search and it stops at the first search. So it's virtually impossible to look for the next occurrence.

Is it possible to load the file with an external editor and save it? Of course I can copy the whole thing to my editor and then paste it back once finished but that's a little cumbersome.

**Comment by kylepaulsen** [comment]
Unfortunately, chrome doesn't allow you to write files to disk to allow file editing in your favorite editor.

I'm using code mirror as the editor currently. I'll try and see if I can make that search dialog stay there. Thanks for the feedback.

**Comment by norbertpy** [comment]
Thanks for your quick response. [ace editor][1] is an alternative to CodeMirror. The `find` feature is very neat. See the demo [here][2]. I find it very easy to use. I have not looked at your code but if I do I might publish a PR for few things.

[1]: https://github.com/ajaxorg/ace
[2]: http://jsfiddle.net/revathskumar/rY37e/

**Comment by kylepaulsen** [comment]
Hey I got a new version coming down the line sometime soon. I remembered a long time ago that I initially wanted to use Ace Editor, but I was having issues. Trying again though, I was able to figure things out!

I think you'll like the new ace editor integration. I certainly do. :)

**Comment by norbertpy** [comment]
Awesome. Let me know when it's ready. It must get really cool. Thanks.

**Comment by kylepaulsen** [comment]
OK v0.6.0 is released. Let me know if you find any bugs. Enjoy the new editor. :)

**Comment by kylepaulsen** [comment]
Closing for now...

**Comment by norbertpy** [comment]
Looks awesome. Thanks.
