### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by dgmaia** [kylepaulsen/ResourceOverride#3]
Most of the labels are coloured in black.
Now that DeveloperTools have a dark theme, its hard to read.

![screen shot 2016-07-20 at 1 50 20 pm](https://cloud.githubusercontent.com/assets/3528298/16972675/7c4477ba-4e81-11e6-86d9-e6c604c667f9.png)

**Comment by kylepaulsen** [comment]
Thanks for reporting. I'll try and fix this soon.

**Comment by kylepaulsen** [comment]
Sorry this took forever.... I just did a new release (v1.0.0) and it should be fixed now.
