### ISSUE TITLE
[BUG] onOff Switch disappeared

### ISSUE THREAD

**Issue by Kageetai** [kylepaulsen/ResourceOverride#35]
![Screenshot 2019-11-26 at 16 28 44](https://user-images.githubusercontent.com/1738309/69647463-d5097a00-1069-11ea-9301-374421eaa9d8.png)
As you can see in the screenshot, the on/off button disappeared in the latest Chrome Canary. It seems it has to do with this error message:
```
Uncaught TypeError: document.registerElement is not a function
    at onOffSwitch.js:8
    at onOffSwitch.js:37
```
https://github.com/kylepaulsen/ResourceOverride/blob/master/src/ui/onOffSwitch.js#L8

I don't really know about this API, but it seems it's deprecated and should be replace with this: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define

**Comment by kylepaulsen** [comment]
Thank you for reporting this. I went ahead and published a fix plus some other changes I had on hand. Not sure when it will go live in the store.

I would greatly appreciate any other bug reports after the new version is live ( v1.1.0 ).

**Comment by Kageetai** [comment]
Ah yes, I see the button is back.
Awesome and thanks for the quick work. With some investigation, I might have been able to fix it myself, but this is surely better.
I quite like your extension and would have been sad, if it would have stayed unusable. :)
